openapi: 3.0.1

paths:

  '/pets/{petId}/events':
    get:
      tags:
        - pets
      operationId: getPetEvents
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            text/event-stream:
              schema:
                type: string
